GET http://localhost:3003/news
Content-Type: application/json

{
    "topic": "bitcoin",
    "language": "pt"
}


###
GET http://localhost:3003/news?limit=10&page=1
Content-Type: application/json

{
    "topic": "apple",
    "language": "pt"
}
